name: Build release version and deploy

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.11.0
        with:
          java-version: 21
          java-distribution: liberica
          checkout-persist-credentials: true
          settings-servers: |
            [{
                "id": "reposilite-releases",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            },
            {
                "id": "reposilite-snapshots",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            }]
      - name: Update version in pom.xml (Release only)
        run: mvn -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build with Maven
        run: mvn spring-boot:build-image -Pnative
      - name: Push Images to Docker Registry
        run: docker push -a ghcr.io/notbjoggisatall/jonasandersen-no

  update:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
                "id": "reposilite-releases",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            },
            {
                "id": "reposilite-snapshots",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            }]

      - name: Bump version to next snapshot version
        run: mvn --batch-mode release:update-versions -DautoVersionSubmodules=true

      - name: Find next snapshot version
        run: echo "NEXT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Push changes and create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          author: github-actions[bot] <$github-actions[bot]@users.noreply.github.com>
          base: master
          branch: "update-version-to-${{ env.NEXT_VERSION }}"
          commit-message: "Update version to ${{ env.NEXT_VERSION }}"
          title: "Update version to ${{ env.NEXT_VERSION }}"
          body: "Update version to ${{ env.NEXT_VERSION }}"