name: Build latest master and deploy

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.11.0
        with:
          java-version: 21
          java-distribution: liberica
          checkout-persist-credentials: true
          settings-servers: |
            [{
                "id": "reposilite-releases",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            },
            {
                "id": "reposilite-snapshots",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            }]
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Maven
        run: mvn spring-boot:build-image -Pnative

      - name: Push Images to Docker Registry
        run: docker push -a bjoggis/jonasandersen-no
      - name: Create and push manifest
        run: |
          docker manifest create bjoggis/jonasandersen-no:${{ github.ref_name }} bjoggis/jonasandersen-no:${{ github.ref_name }}-x86_64
          docker manifest push bjoggis/jonasandersen-no:${{ github.ref_name }}
          docker manifest create bjoggis/jonasandersen-no:latest bjoggis/jonasandersen-no:${{ github.ref_name }}-x86_64
          docker manifest push bjoggis/jonasandersen-no:latest